### PR TITLE
Making homepage translatable. And updating files in i18n

### PR DESCRIPTION
**Pull request by 0xMRTT**

### CODE REVIEW

**Comment by 0xMRTT** [comment]
Please don't merge the latest commit.

**Comment by ss-o** [comment]
> Please don't merge the latest commit.

Could you open a new PR?

**Comment by ss-o** [comment]
Additionally, files in `i18n/*` must be updated through crowdin (uploaded), otherwise, it will be overwritten. Let me know if you need help with this one.

**Comment by 0xMRTT** [comment]
I think that i can upload files for french but i can't for others languages. I will upload french soon. Could you upload others files ?

**Comment by 0xMRTT** [comment]
> > Please don't merge the latest commit.
> 
> Could you open a new PR?

I will open a new PR soon with only modifications of the homepage.

**Comment by ss-o** [comment]
> I think that i can upload files for french but i can't for others languages. I will upload french soon. Could you upload others files ?

When you open new PR, we will see how we can improve and automate this :octocat:

**Comment by 0xMRTT** [comment]
#672: close this PR.

**Pull request closed without merging**
