### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ss-o**

### CODE REVIEW

**Comment by ss-o** [comment]
Hey,:wave:

Just wanted to let you know about translations, so you do not accidentally spend time as it would be pointless. I automated translations with AI and ML it requires just confirmation from a native speaker, I put some notes here: https://github.com/z-shell/zw/blob/fd1430ace7820cc047909c6821ba874e3cc8ce85/.github/README.md#translations

Now it requires just a few minutes to translate docs - no pull requests etc. I have so many to introduce to ZI, but it's pointless until it is well documented in the first place. So 5 minutes of your time means a lot for me and others. As all automated, I don't need to mention you here to approve :smile: so if you decide to contribute your minute or two the link above has information where to start :upside_down_face:. If any additional support is required or I can help with something - just mention me and I am there for you :+1: Thanks again! :heart: 

@yutkat, @lunarxlark, @the-ryujin, 

Sincerely,

**Comment by the-ryujin** [comment]
You have a lot of computing power as I know, so could give Google Cloud or Cloudflare Pro for membership for a year :smile:. Joking I still own you from last time :handshake:  it fun to collaborate and make something good happen :)

**Comment by wicoop** [comment]
@ss-o,  it is easy for you when most of what you do is done by bots or etc., automatically, I lost count of your services and accounts a long time ago :see_no_evil: :robot: :space_invader:

**Comment by ss-o** [comment]
I always say: Perfection is achieved not when there is nothing more to add, but rather when there is nothing more to take away and has a good deep meaning :octocat:

**Comment by ss-o** [comment]
Register for the professional course to get Google Badges on your profile: https://inthecloud.withgoogle.com/google-cloud-skills/register.html

**Comment by anwalk** [comment]
That course is quite hard, but really valuable, and those badges you can put almost anywhere, I added to LinkedIn and g.dev of course :) awesome!

**Pull request merged**
